#!/bin/bash

NAME=$(zenity --entry --title="Theme Saver" --text="Enter the name to identify the save as.\nThis will make it easier to indentify your theme layout.")
if [ ! -z "$NAME" ]; then
mkdir ~/.feren-layout-backups
cd ~/.feren-layout-backups
if [ -d "./$NAME" ]; then
	rm -rf "./$NAME"
fi
mkdir "./$NAME"
cd "./$NAME"
echo "Backing Up Applets Layout"
touch "applets"
echo $(gsettings get org.cinnamon enabled-applets) > "applets"
echo "Backing Up Extensions"
touch "extensions"
echo $(gsettings get org.cinnamon enabled-extensions) > "extensions"
echo "Backing Up Favourite Applications"
touch "fav-apps"
echo $(gsettings get org.cinnamon favorite-apps) > "fav-apps"
echo "Backing Up Panels"
touch "panels"
echo $(gsettings get org.cinnamon panels-enabled) > "panels"
touch "panels-ah"
echo $(gsettings get org.cinnamon panels-autohide) > "panels-ah"
touch "panels-h"
echo $(gsettings get org.cinnamon panels-height) > "panels-h"
touch "panels-r"
echo $(gsettings get org.cinnamon panels-resizable) > "panels-r"
touch "panels-sti"
echo $(gsettings get org.cinnamon panels-scale-text-icons) > "panels-sti"
echo "Backing up Theme & Theme Settings"
touch "cinn-theme"
echo $(gsettings get org.cinnamon.theme name) > "cinn-theme"
touch "cur-theme"
echo $(gsettings get org.cinnamon.desktop.interface cursor-theme) > "cur-theme"
touch "gtk-layout"
echo $(gsettings get org.cinnamon.desktop.interface gtk-decoration-layout) > "gtk-layout"
touch "gtk-theme"
echo $(gsettings get org.cinnamon.desktop.interface gtk-theme) > "gtk-theme"
touch "icon-theme"
echo $(gsettings get org.cinnamon.desktop.interface icon-theme) > "icon-theme"
touch "wm-theme"
echo $(gsettings get org.cinnamon.desktop.wm.preferences theme) > "wm-theme"
touch "wm-layout"
echo $(gsettings get org.cinnamon.desktop.wm.preferences) > "wm-layout"
echo "Saving ALL Applet, Extensions, ETC Configurations"
mkdir "./thing-configs"
cp -R ~/.cinnamon/configs/* "./thing-configs"

echo ""
echo "Done, Theme Layout was backed up as '$NAME'."

fi
